.TH ALSOFT-CONF 1 "December 10, 2009"
.SH NAME
alsoft-conf \- OpenAL-Soft configuration utility
.SH SYNOPSIS
.B alsoft-conf
.br
.SH DESCRIPTION
.PP
\fBalsoft-conf\fP is GUI program written with Qt4 meant to aid in configuring OpenAL-Soft.
.SH SEE ALSO
.BR alsoft.conf (5).
.br
.SH AUTHOR
alsoft-conf was written by Matias D'Ambrosio <angasule@gmail.com>.
.PP
This manual page was written by Matias D'Ambrosio <angasule@gmail.com>,
for the Debian project (and may be used by others).
